#!/usr/bin/env python3
"""Fetch the ANCP research source corpus.

The fetched pages are evidence snapshots for local protocol work. They are not
vendored docs for redistribution as a separate documentation product.
"""

from __future__ import annotations

import json
import pathlib
import time
import urllib.error
import urllib.request


ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCES_PATH = ROOT / "research" / "source-docs" / "sources.json"
SNAPSHOT_ROOT = ROOT / "research" / "source-docs" / "snapshots"
REPORT_PATH = ROOT / "research" / "source-docs" / "fetch-report.json"
INDEX_PATH = ROOT / "research" / "source-docs" / "index.md"
FETCH_ATTEMPTS = 3


def fetch(url: str) -> tuple[int | None, bytes, str | None]:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "ANCP-Research-Corpus/1.0 (+https://github.com/agent-native-compiler-protocol)",
            "Accept": "text/html,text/plain,text/markdown,application/json,*/*;q=0.8",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=40) as response:
            return response.status, response.read(), None
    except urllib.error.HTTPError as exc:
        body = exc.read() if exc.fp else b""
        return exc.code, body, str(exc)
    except Exception as exc:  # noqa: BLE001 - report fetch failures without stopping the corpus pass.
        return None, b"", str(exc)


def fetch_with_retries(url: str) -> tuple[int | None, bytes, str | None, int]:
    last_status: int | None = None
    last_body = b""
    last_error: str | None = None
    for attempt in range(1, FETCH_ATTEMPTS + 1):
        status, body, error = fetch(url)
        last_status, last_body, last_error = status, body, error
        ok = bool(status and 200 <= status < 400 and body)
        retryable = status is None or status in {408, 425, 429} or bool(status and 500 <= status < 600)
        if ok or not retryable or attempt == FETCH_ATTEMPTS:
            return status, body, error, attempt
        time.sleep(1.5 * attempt)
    return last_status, last_body, last_error, FETCH_ATTEMPTS


def main() -> int:
    sources = json.loads(SOURCES_PATH.read_text(encoding="utf-8"))
    SNAPSHOT_ROOT.mkdir(parents=True, exist_ok=True)

    report = []
    for source in sources:
        output = SNAPSHOT_ROOT / source["local"]
        output.parent.mkdir(parents=True, exist_ok=True)

        started = time.time()
        status, body, error, attempts = fetch_with_retries(source["url"])
        elapsed_ms = round((time.time() - started) * 1000)

        ok = bool(status and 200 <= status < 400 and body)
        if ok:
            output.write_bytes(body)

        report.append(
            {
                "id": source["id"],
                "title": source["title"],
                "url": source["url"],
                "local": str(output.relative_to(ROOT)).replace("\\", "/"),
                "status": status,
                "ok": ok,
                "bytes": len(body),
                "elapsedMs": elapsed_ms,
                "attempts": attempts,
                "error": error,
            }
        )

    REPORT_PATH.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")

    lines = [
        "# Source Document Index",
        "",
        "Generated by `python tools/fetch_sources.py`.",
        "",
        "| ID | Title | Status | Local Snapshot | URL |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in report:
        status_text = "ok" if item["ok"] else f"failed:{item['status'] or 'n/a'}"
        lines.append(
            f"| `{item['id']}` | {item['title']} | {status_text} | "
            f"`{item['local']}` | {item['url']} |"
        )
    INDEX_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    failed = [item for item in report if not item["ok"]]
    if failed:
        print(f"Fetched {len(report) - len(failed)}/{len(report)} source documents; {len(failed)} failed.")
        for item in failed:
            print(f"FAILED {item['id']}: status={item['status']} error={item['error']}")
        return 1

    print(f"Fetched {len(report)}/{len(report)} source documents.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
